env:
  _target_: aspire.sim.cap.envs.tasks.f1tenth.levine_lap.F1TenthLevineCodeEnv
  cfg:
    _target_: aspire.sim.cap.envs.tasks.base.CodeExecEnvConfig
    low_level:
      _target_: aspire.sim.cap.envs.simulators.f1tenth.F1TenthLevineLowLevel
      max_steps: 18000
      control_repeat: 5
      seed: 101
      privileged: true
      enable_render: true
      render_size: 384
      video_stride: 4
    privileged: true
    enable_render: true
    apis:
      - F1TenthControlApiTraced

record_video: true
use_visual_feedback: false
use_img_differencing: false
use_parallel_ensemble: false
use_multimodel: false
output_dir: ./outputs/f1tenth/levine_privileged
trials: 1
num_workers: 1
